vault:
  enabled: true
  global:
    tlsDisable: false
    openshift: true
  injector:
    enabled: false
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
      tag: "1.4.2-ubi"
    agentImage:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.18.0-ubi"
  ui:
    enabled: true
  server:
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.18.0-ubi"
    route:
      enabled: true
      host:
    extraEnvironmentVars:
      VAULT_CACERT: "/etc/vault-tls/vault-certs/ca.crt"
      VAULT_TLS_SERVER_NAME:
    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/etc/vault-tls/vault-certs/tls.crt"
          tls_key_file = "/etc/vault-tls/vault-certs/tls.key"
          tls_client_ca_file = "/etc/vault-tls/vault-certs/ca.crt"
        }
        storage "file" {
          path = "/vault/data"
        }
    auditStorage:
      enabled: false
      size: 5Gi
    extraVolumes:
      - type: "secret"
        name: "vault-certs"
        path: "/etc/vault-tls"
    ha:
      enabled: false
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/etc/vault-tls/vault-certs/tls.crt"
            tls_key_file = "/etc/vault-tls/vault-certs/tls.key"
            tls_client_ca_file = "/etc/vault-tls/vault-certs/ca.crt"
          }
          storage "raft" {
            path = "/vault/data"
            retry_join {
              leader_api_addr = "https://vault-active.hashicorp.svc:8200"
              leader_ca_cert_file = "/etc/vault-tls/vault-certs/ca.crt"
            }
          }
          log_level = "debug"
          service_registration "kubernetes" {}
    service:
      enabled: true
    tolerations[0]:
      operator: Exists
      effect: NoSchedule
