---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: int-ca-issuer
  namespace: vault
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
spec:
  ca:
    secretName: intermediate
