---

helmCharts:
  - name: vault
    namespace: vault
    includeCRDs: false
    valuesFile: charts/vault/values.yaml
    version: 0.0.1
    releaseName: vault
    repo:  # we expand chart in folder
    valuesInline:
      vault:
        server:
          route:
            host: vault.apps.cushen-demo.sandbox2001.opentlc.com
          extraEnvironmentVars:
            VAULT_TLS_SERVER_NAME: vault.apps.cushen-demo.sandbox2001.opentlc.com
