apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: hosted
  namespace: hosted
spec:
  clusterDeploymentRef:
    name: hosted
  imageSetRef:
    name: img4.19.0-multi-appsub
  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.130.0/24
    networkType: OVNKubernetes
    serviceNetwork:
      - 172.30.0.0/16
    userManagedNetworking: true
  provisionRequirements:
    controlPlaneAgents: 1
  platformType: None
  sshPublicKey: <ssh_key>