apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: hosted
  namespace: hosted
  labels:
    cluster.open-cluster-management.io/clusterset: default
    hive.openshift.io/cluster-platform: none-platform
spec:
  baseDomain: sno.redhatlabs.dev
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: hosted
    version: v1beta1
  clusterName: hosted
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  platform:
    none: {}
  pullSecretRef:
    name: pullsecret-cluster-hosted