apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: hosted
  namespace: hosted
spec:
  clusterRef:
    name: hosted
    namespace: hosted
  cpuArchitecture: x86_64
  imageType: full-iso
  ipxeScriptType: DiscoveryImageAlways
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: acm-sno-0
  pullSecretRef:
    name: pullsecret-cluster-hosted
  sshAuthorizedKey: <ssh_key>