---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  labels:
    cluster-name: acm-sno-0
  name: acm-sno-0
  namespace: hosted
spec:
  config:
    dns-resolver:
      config:
        server:
          - 192.168.130.1
    interfaces:
      - ipv4:
          address:
            - ip: 192.168.130.10
              prefix-length: 24
          dhcp: false
          enabled: true
        mac-address: '52:54:00:22:4d:4a'
        name: enp1s0
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.130.1
          next-hop-interface: enp1s0
          table-id: 254
  interfaces:
    - macAddress: '52:54:00:22:4d:4a'
      name: enp1s0