name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy OpenShift & Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Create S3 Bucket
        run: |
          BUCKET_NAME="ocpdeploy-$(date +%Y-%m-%d-%H-%M-%S)"
          aws s3 mb s3://$BUCKET_NAME
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          echo "Created S3 bucket: $BUCKET_NAME"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Setup Working Directory for OCP Install
        run: |
          mkdir ocp-artifact
          sed -i 's/RED_HAT_PULLSECRET/${{ secrets.RED_HAT_PULLSECRET }}/' install-config.yaml
          sed -i 's/OCP_BASE_DOMAIN/${{ secrets.OCP_BASE_DOMAIN }}/' install-config.yaml
          sed -i 's/OCP_CLUSTER_NAME/${{ secrets.OCP_CLUSTER_NAME }}/' install-config.yaml
          sed -i 's/AWS_REGION/${{ secrets.AWS_REGION }}/' install-config.yaml
          cp install-config.yaml ocp-artifact/

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{ secrets.OCP_CLIENT_VERSION }}"
          oc: "${{ secrets.OCP_CLIENT_VERSION }}"

      - name: Create OpenShift Cluster
        run: openshift-install create cluster --skip-password-print --dir=ocp-artifact/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Setup HTPasswd IDP
        run: |
          export KUBECONFIG=ocp-artifact/auth/kubeconfig
          htpasswd -c -b -B htpasswd ${{ secrets.OCP_ADMIN_USER }} ${{ secrets.OCP_ADMIN_PASS }}
          oc create secret generic htpass-secret --from-file=htpasswd=htpasswd -n openshift-config --dry-run=client -o yaml | oc apply -f -
          oc apply -f auth/cluster-oauth.yaml
          sleep 200
          oc adm policy add-cluster-role-to-user cluster-admin ${{ secrets.OCP_ADMIN_USER }}

      - name: Upload Artifacts to S3
        run: |
          aws s3 cp --recursive ocp-artifact/ s3://$BUCKET_NAME/ocp-artifact/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ env.BUCKET_NAME }}