name: Deploy
on:
  workflow_dispatch:

jobs:
  Setup:
    name: Setup OpenShift Installer Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Setup Working Directory for OCP Install
        run: |
          sed -i 's/RED_HAT_PULLSECRET/${{ secrets.RED_HAT_PULLSECRET }}/' install-config.yaml > /dev/null 2>&1
          sed -i 's/OCP_BASE_DOMAIN/${{ secrets.OCP_BASE_DOMAIN }}/' install-config.yaml > /dev/null 2>&1
          sed -i 's/OCP_CLUSTER_NAME/${{ secrets.OCP_CLUSTER_NAME }}/' install-config.yaml > /dev/null 2>&1
          sed -i 's/AWS_REGION/${{ secrets.AWS_REGION }}/' install-config.yaml > /dev/null 2>&1
          mkdir ocp-artifact
          cp install-config.yaml ocp-artifact/

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{secrets.OCP_CLIENT_VERSION}}"
          oc: "${{secrets.OCP_CLIENT_VERSION}}"
      
      - name: Create OpenShift Cluster
        run: openshift-install create cluster --dir=ocp-artifact/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Save Artifacts for Destroy
        uses: actions/upload-artifact@v4
        with:
          name: ocp-artifact
          path: ocp-artifact

      - name: Setup HTPasswd IDP
        run: |
          export KUBECONFIG=ocp-artifact/auth/kubeconfig
          echo "Creating htpasswd file"
          htpasswd -c -b -B htpasswd ${{ secrets.OCP_ADMIN_USER }} ${{ secrets.OCP_ADMIN_PASS }}
          oc create secret generic htpass-secret --from-file=htpasswd=htpasswd -n openshift-config --dry-run=client -o yaml | oc apply -f -
          oc apply -f cluster-oauth.yaml
          sleep 300
          oc adm policy add-cluster-role-to-user cluster-admin ${{ secrets.OCP_ADMIN_USER }}
          oc adm policy add-cluster-role-to-user cluster-admin -z openshift-gitops-argocd-application-controller