name: Deploy
on:
  workflow_dispatch:

jobs:
  create_s3_bucket:
    name: Create S3 Bucket for OCP Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Create S3 Bucket
        run: |
          BUCKET_NAME="ocpdeploy-$(date +%Y-%m-%d-%H-%M-%S)"
          aws s3 mb s3://$BUCKET_NAME
          echo "Created S3 bucket: $BUCKET_NAME"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  deploy:
    name: Setup and Deploy OpenShift Cluster
    runs-on: ubuntu-latest
    needs: create_s3_bucket  # Ensures this job runs after create_s3_bucket
    steps:
      - uses: actions/checkout@main
      - name: Setup Working Directory for OCP Install
        run: |
          sed -i 's/RED_HAT_PULLSECRET/${{ secrets.RED_HAT_PULLSECRET }}/' install-config.yaml > /dev/null 2>&1
          sed -i 's/OCP_BASE_DOMAIN/${{ secrets.OCP_BASE_DOMAIN }}/' install-config.yaml > /dev/null 2>&1
          sed -i 's/OCP_CLUSTER_NAME/${{ secrets.OCP_CLUSTER_NAME }}/' install-config.yaml > /dev/null 2>&1
          sed -i 's/AWS_REGION/${{ secrets.AWS_REGION }}/' install-config.yaml > /dev/null 2>&1
          mkdir ocp-artifact
          cp install-config.yaml ocp-artifact/

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{ secrets.OCP_CLIENT_VERSION }}"
          oc: "${{ secrets.OCP_CLIENT_VERSION }}"

      - name: Create OpenShift Cluster
        run: openshift-install create cluster --skip-password-print --dir=ocp-artifact/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Setup HTPasswd IDP
        run: |
          export KUBECONFIG=ocp-artifact/auth/kubeconfig
          echo "Creating htpasswd file"
          htpasswd -c -b -B htpasswd ${{ secrets.OCP_ADMIN_USER }} ${{ secrets.OCP_ADMIN_PASS }}
          oc create secret generic htpass-secret --from-file=htpasswd=htpasswd -n openshift-config --dry-run=client -o yaml | oc apply -f -
          oc apply -f auth/cluster-oauth.yaml

  upload_artifacts_to_s3:
    name: Upload Artifacts to S3
    runs-on: ubuntu-latest
    needs: deploy  # Ensures this job runs after deploy
    steps:
      - name: Upload Artifacts to S3
        run: |
          aws s3 cp --recursive ocp-artifact/ s3://$BUCKET_NAME/ocp-artifact/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}