name: Destroy
on:
  workflow_dispatch:

jobs:
  Setup:
    name: Setup OpenShift Installer Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download OCP Cluster Artifacts
        uses: dawidd6/action-download-artifact@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: deploy.yaml
#          workflow_conclusion: failure
          branch: main
          name: ocp-artifact
          path: .
          check_artifacts:  false

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{ secrets.OCP_CLIENT_VERSION }}"

      - name: Destroy OpenShift Cluster
        run: openshift-install destroy cluster --dir=.
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}